recipes.remove(<xreliquary:fortune_coin>);
recipes.addShapeless(<xreliquary:fortune_coin>, [<xreliquary:mob_ingredient:11>, <minecraft:gold_nugget>, <xreliquary:mob_ingredient:4>, <xreliquary:mob_ingredient:5>,<iceandfire:deathworm_tounge>]);
recipes.remove(<xreliquary:salamander_eye>);
recipes.addShapeless(<xreliquary:salamander_eye>, [<minecraft:ender_eye>, <xreliquary:mob_ingredient:7>, <xreliquary:mob_ingredient:10>, <xreliquary:mob_ingredient:11>,<iceandfire:cockatrice_eye>,<twilightforest:fiery_blood>]);
recipes.remove(<xreliquary:hero_medallion>);
recipes.addShapeless(<xreliquary:hero_medallion>, [<xreliquary:mob_ingredient:11>, <xreliquary:fortune_coin>, <xreliquary:witch_hat>, <xreliquary:infernal_tear>,<iceandfire:hippogryph_talon>,<tombstone:crafting_ingredient:2>]);
recipes.remove(<xreliquary:mob_ingredient:13>);
recipes.addShapeless(<xreliquary:mob_ingredient:13>, [<minecraft:leather>, <xreliquary:mob_ingredient:7>, <xreliquary:mob_ingredient>, <xreliquary:mob_ingredient:4>,<iceandfire:fire_dragon_blood>]);
recipes.remove(<xreliquary:void_tear>);
recipes.addShapeless(<xreliquary:void_tear>, [<minecraft:ghast_tear>, <xreliquary:mob_ingredient:11>, <xreliquary:mob_ingredient:4>, <minecraft:dye:4>,<iceandfire:siren_tear>]);
recipes.remove(<xreliquary:mob_ingredient:9>);
recipes.addShapeless(<xreliquary:mob_ingredient:9>, [<xreliquary:mob_ingredient>, <xreliquary:mob_ingredient:3>, <minecraft:dye:2>, <xreliquary:mob_ingredient:4>,<iceandfire:pixie_wings>]);
recipes.remove(<xreliquary:mob_ingredient:14>);
recipes.addShapeless(<xreliquary:mob_ingredient:14>, [<xreliquary:mob_ingredient:12>, <xreliquary:mob_ingredient:12>, <xreliquary:mob_ingredient:12>, <xreliquary:mob_ingredient:4>,<iceandfire:hippocampus_fin>]);
recipes.remove(<xreliquary:rending_gale>);
recipes.addShaped(<xreliquary:rending_gale>, [[<xreliquary:mob_ingredient:14>, <xreliquary:mob_ingredient:5>, <xreliquary:mob_ingredient:8>], [<minecraft:gold_ingot>, <xreliquary:void_tear>, <xreliquary:mob_ingredient:5>], [<minecraft:stick>, <minecraft:gold_ingot>, <xreliquary:mob_ingredient:14>]]);
recipes.remove(<tombstone:crafting_ingredient:2>);
recipes.addShaped(<tombstone:crafting_ingredient:2>, [[<ore:dustGrave>, <ore:gemRuby>, <ore:dustGrave>], [<ore:gemSapphire>, <ore:gemDiamond>, <ore:gemJade>], [<ore:dustGrave>, <ore:gemAmethyst>, <ore:dustGrave>]]);
